### ISSUE TITLE
Slow performance on HelloWorld sample

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#1109]
## Description

Mythril takes a long time (4m47s on my Mac with `--loop-bound 2`) for this sample:

```
pragma solidity ^ 0.5.2;

contract HelloWorld {

   event SayHello(address id, string userMessage);

   struct Participant {
      address participant;
      uint value;
   }

   address payable public owner;
   Participant[] public participants;

   constructor() public payable {
      owner = msg.sender;
   }

   function helloWorld(string memory _userMessage) public returns(string memory) {
      emit SayHello(msg.sender, _userMessage);
      return _userMessage; //Only calls will return this as result
   }

   function sendETHToContract() public payable {
      Participant memory participant;
      participant.participant = msg.sender;
      participant.value = msg.value;
      participants.push(participant);
   }

   function sendContractETHToOwner() public {
      owner.transfer(address(this).balance);
      delete participants;
   }
}
```

## How to Reproduce

```
$ time $MYTH -v4 analyze HelloWorld.sol --loop-bound 2
==== Exception State ====
SWC ID: 110
Severity: Low
Contract: HelloWorld
Function name: participants(uint256)
PC address: 869
Estimated Gas Usage: 645 - 740
A reachable exception has been detected.
It is possible to trigger an exception (opcode 0xfe). Exceptions can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. Note that explicit `assert()` should only be used to check invariants. Use `require()` for regular input checking.
--------------------
In file: HelloWorld.sol:13

] public participants;

   constr

--------------------
Transaction Sequence:

Caller: [CREATOR], data: [CONTRACT CREATION], value: 0x0
Caller: [ATTACKER], data: 0x1706f851, value: 0x0
Caller: [CREATOR], data: 0x35c1d3498000000000000000000000000000000000000000000000000000000000000000, value: 0x0


real	4m47.807s
user	4m23.480s
sys	0m3.906s
```

## Expected behavior

Perhaps some optimizations are possible here (memory?).

## Environment

- Mythril version: Develop
- Solidity compiler and version: 0.5.7
- Python version:. 3.6.3
- OS and Version: Mac OS Mojave

**Comment by norhh** [comment]
Concating the word is taking some time, perhaps we can store concatenated bytes by default in some cache sort of memory which can be directly used.

**Comment by FranzHuebner** [comment]
Hey, as mentioned yesterday I can provide more samples which take an unusual time to proceed.

```pragma solidity ^0.5;

contract Proxybad {

  address owner;

  constructor() public {
    owner = msg.sender;  
  }

  function forward(address callee, bytes memory _data) public {
    callee.delegatecall(_data);
  }

}


contract Proxybetter {

  address callee;
  address owner;

  modifier onlyOwner {
    require(msg.sender == owner);
    _;
  }

  constructor() public {
    callee = address(0x0);
    owner = msg.sender;
  }

  function setCallee(address newCallee) public onlyOwner {
    callee = newCallee;
  }

  function forward(bytes memory _data) public {
    (bool success, bytes memory returnData) = callee.call(_data);
    require(success, "external contract failed");
    require(returnData.length == 0,"external contract return data is not null");

  }

}
```
Results in

```==== Delegatecall Proxy To User-Supplied Address ====
SWC ID: 112
Severity: Medium
Contract: swc112_untrusted_call
Function name: forward(address,bytes)
PC address: 391
Estimated Gas Usage: 1871 - 40385
The contract delegates execution to another contract with a user-supplied address.
The smart contract delegates execution to a user-supplied address. Note that callers can execute arbitrary contracts and that the callee contract can access the storage of the calling contract. 
--------------------
In file: /tmp/swc112_untrusted_call.sol:12

gatecall(_data);
  }

}

/

--------------------

==== Unchecked Call Return Value ====
SWC ID: 104
Severity: Low
Contract: swc112_untrusted_call
Function name: forward(address,bytes)
PC address: 391
Estimated Gas Usage: 1871 - 40385
The return value of a message call is not checked.
External calls return a boolean value. If the callee contract halts with an exception, 'false' is returned and execution continues in the caller. It is usually recommended to wrap external calls into a require statement to prevent unexpected states.
--------------------
In file: /tmp/swc112_untrusted_call.sol:12

gatecall(_data);
  }

}

/

--------------------

==== External Call To Fixed Address ====
SWC ID: 107
Severity: Low
Contract: Proxybetter
Function name: forward(bytes)
PC address: 634
Estimated Gas Usage: 1475 - 6036
The contract executes an external message call.
An external function call to a fixed contract address is executed. Make sure that the callee contract has been reviewed carefully.
--------------------
In file: /tmp/swc112_untrusted_call.sol:40

s, "external contr

--------------------


```
0.15user 0.18system **10:19.84elapsed** 0%CPU (0avgtext+0avgdata 49708maxresident)k
16440inputs+0outputs (76major+6851minor)pagefaults 0swaps

-> Takes around 10 to 15 minutes under normal settings in my ubuntu 16 vm with mythril docker.

There is another big contract (500 lines) with a lot of inheritance going on which takes around 15 minutes, but I think this is pretty normal for the size. The contract is nearly the same as [https://github.com/SmartContractSecurity/SWC-registry/blob/master/entries/SWC-125.md](url)



I still have the problem that the whole pipeline fails with no output when mythril starts with the HelloWorld contract, but when its start with an easy contract every contract will proceed in a slow but normal way without errors and the desired output.

-> When I find more information regarding the problem, I will open up another issue.

**Comment by norhh** [comment]
Hey @FranzHuebner thanks for the report, We will fix it soon. Meanwhile you can set a timeout when analyzing large contracts by using `./myth -x <filename> --execution-timeout <seconds>`

**Comment by b-mueller** [comment]
@FranzHuebner Mythril v0.21.5 should fix the slowdowns. Locally I'm getting the following times:

- helloworld.sol -> 1m7s
- proxy.sol -> 55s

Can you try to confirm this?

**Comment by FranzHuebner** [comment]
Hey @b-mueller @norhh 

- helloworld.sol -> from 20m to 2m10s under ubuntu 16

- proxy.sol -> from 10/15m to 4m36s under ubuntu 16

Under CentOS my pipeline still fails with following error:
```
mythril.interfaces.cli [ERROR]: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.21.5-py3.6.egg/mythril/interfaces/cli.py", line 658, in parse_args_and_execute
    config = set_config(args)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.21.5-py3.6.egg/mythril/interfaces/cli.py", line 434, in set_config
    config = MythrilConfig()
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.21.5-py3.6.egg/mythril/mythril/mythril_config.py", line 26, in __init__
    self.mythril_dir = self._init_mythril_dir()
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.21.5-py3.6.egg/mythril/mythril/mythril_config.py", line 55, in _init_mythril_dir
    copyfile(str(asset_dir / "signatures.db"), db_path)
  File "/usr/lib/python3.6/shutil.py", line 122, in copyfile
    copyfileobj(fsrc, fdst)
  File "/usr/lib/python3.6/shutil.py", line 82, in copyfileobj
    fdst.write(buf)
OSError: [Errno 28] No space left on device
```

Without these specific contracts overall time went from 20 minutes to 12 minutes.

**Comment by b-mueller** [comment]
@FranzHuebner if that's too long you can still force an execution timeout like @norhh suggested above, e.g. `--execution-timeout 90`. It will cut analysis short in some cases so it's a tradeoff between coverage and analysis speed.

Can you create a separate bug report for the CentOS thing?

**Comment by FranzHuebner** [comment]
> Can you create a separate bug report for the CentOS thing?

Will do when I have time. 

ATM I will stick with the suggestion from @norhh to force an execution time after some minutes.

Thanks for the help :+1:

**Comment by b-mueller** [comment]
Of course. Thanks for the bug report :)
