### ISSUE TITLE
Mythril crashes with unicode error

### ISSUE THREAD

**Issue by shashank-srikant** [ConsenSys/mythril#448]
## Description
For this source file https://etherscan.io/address/0x39e8082b00c9f19ebf553e40feb7cf8459acc693#code, running `myth -xo json filename` produces the following error -
```
Traceback (most recent call last):
  File "/usr/local/bin/myth", line 11, in <module>
    load_entry_point('mythril==0.18.11', 'console_scripts', 'myth')()
  File "/usr/local/lib/python3.5/dist-packages/mythril/interfaces/cli.py", line 209, in main
    max_depth=args.max_depth, execution_timeout=args.execution_timeout)
  File "/usr/local/lib/python3.5/dist-packages/mythril/mythril.py", line 385, in fire_lasers
    issue.add_code_info(contract)
  File "/usr/local/lib/python3.5/dist-packages/mythril/analysis/report.py", line 38, in add_code_info
    codeinfo = contract.get_source_info(self.address)
  File "/usr/local/lib/python3.5/dist-packages/mythril/ether/soliditycontract.py", line 112, in get_source_info
    code = solidity_file.data.encode('utf-8')[offset:offset + length].decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 0: invalid start byte
```
It is probably because of Hanzi characters in the comments of this code.

## Expected behavior

Mythril is not supposed to crash here.

## Environment
- Mythril version: https://github.com/ConsenSys/mythril/commit/657458bda31a868c54c8966a98b4b6a1ba841abd
- Solidity compiler and version: `Version: 0.4.24+commit.e67f0147.Linux.g++`
- Python version: `Python 3.5.2`
- OS: Ubuntu 16.04 LTS

**Comment by norhh** [comment]
Thats quite interesting, for me it is running properly for both python3.5 and 3.6, can you try upgrading solc version to 0.4.25 and then retry it again?

**Comment by norhh** [comment]
oops looks like it isn't available on npm or releases, i have no clue how i have that version, probably installed it straight from github

**Comment by norhh** [comment]
can you try checking whether `solc --hashes` exists for that version or not?

**Comment by shashank-srikant** [comment]
tried it. it's just been running for a while now..

**Comment by norhh** [comment]
can you try rechecking it with the master?As that stack error bug was fixed

**Comment by shashank-srikant** [comment]
I face this even on the current master.
not sure what's going on here.

**Comment by norhh** [comment]
Can you check whether it crashes for this contract `0xb75a5e36cC668bC8Fe468e8f272Cd4a0fd0fd773`

**Comment by shashank-srikant** [comment]
i get a `No contract was created during the execution of contract creation Try to increase the resouces for creation exection (max-depth or create_timeout)` message.
Tried tweaking both, `max-depth` and `create-timeout` with various values; in vain.

**Comment by JoranHonig** [comment]
@shashank-srikant That might be caused by the same problem as #440, which is fixed with #463 (not merged yet)

**Comment by norhh** [comment]
#463 doesn't seem to fix it, seems to be a different problem.

**Comment by norhh** [comment]
@shashank-srikant ,can you send me the exact file, there might be a chance that some os/editor specific character might be causing the problem.
Also can you check it with the mythril docker image if it is raising any problem.

**Comment by norhh** [comment]
@shashank-srikant , are you running it on `python 3.5.2` ? because i think there exists a problem with that version of python, But in this case i am not even sure mythril would run with that version of python, 
Can you recheck it, also can you try repeating the same in python 3.6 or python 3.5.3+ to check whether this problem exists or not?

**Comment by shashank-srikant** [comment]
No, still see the same error.
Although - it fixed #478!

**Comment by norhh** [comment]
can you please help us by running the below code in your PC and say whether it produces an error or not, just to confirm that whether my pc is slow to detect that issue which lead to error or it's some dependency issue.

```
// 使用说明
contract TimeLock {//5确认锁仓时间是否到了，结束锁仓.开始发行使用说明
 /*使用说明*/   mapping(address => uint) /*使用说明*/ public /*使用说明*/ balances; //5确认锁仓时间是否到了，结束锁仓.开始发行使用说明
   /*使用说明*/ mapping(address => uint) /*使用说明*/ public /*使用说明*/ lockTime;  //5确认锁仓时间是否到了，结束锁仓.开始发行使用说明
    function deposit() public payable {
/* 使用说明 */balances[msg.sender] /* 确认锁仓时间是否到了，结束锁仓 */ += /*使用说明*/ msg.value;
   /*使用说明*/     lockTime[msg.sender] = /*使用说明*/ now + /*使用说明*/ 1 weeks;
   /*使用说明*/ }
    //5确认锁仓时间是否到了，结束锁仓.开始发行使用说明
    function increaseLockTime(uint _secondsToIncrease) /*使用说明*/ public {
        //5确认锁仓时间是否到了，结束锁仓.开始发行使用说明
        lockTime[msg.sender] += /*//5确认锁仓时间是否到了，结束锁仓.开始发行使用说明*/_secondsToIncrease;// 使用说明
    // 确认锁仓时间是否到了，结束锁仓
/*使用说明*/    }
/*5确认锁仓时间是否到了，结束锁仓.开始发行使用说明*/    function withdraw() public { ////5确认锁仓时间是否到了，结束锁仓.开始发行使用说明
        require(balances[msg.sender] > 0); //使用说明
        /*使用说明*/ require(now > lockTime[msg.sender]); //使用说明
        /*使用说明*/ balances[msg.sender] = /*使用说明*/ 0; //使用说明
        /*确认锁仓时间是否到了，结束锁仓*/ msg.sender.transfer(balances[msg.sender]); //确认锁仓时间是否到了，结束锁仓
  /*使用说明*/  } //确认锁仓时间是否到了，结束锁仓
} //确认锁仓时间是否到了，结束锁仓
```

**Comment by shashank-srikant** [comment]
works fine on my machine.
this is the output i see.
```
{"error": null, "issues": [{"address": 817, "code": "lockTime[msg.sender] += /*//5\u786e\u8ba4\u9501\u4ed3\u65f6\u95f4\u662f\u5426\u5230\u4e86\uff0c\u7ed3\u675f\u9501\u4ed3.\u5f00\u59cb\u53d1\u884c\u4f7f\u7528\u8bf4\u660e*/_secondsToIncrease", "contract": "TimeLock", "debug": "storage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0x744240060f11ee8302555055dccca6b72611ae29090e239231b0a7b8f29ae057\ncalldata_TimeLock[4]: 0xd7ee0142c5f24581862400cc4785a2910417ad282802609755ac30ac4c9e435d\ncalldata_TimeLock[0]: 0x79af55e400000000000000000000000000000000000000000000000000000000\ncalldatasize_TimeLock: 0x4\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `increaseLockTime(uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "sol_unicode.sol", "function": "increaseLockTime(uint256)", "lineno": 12, "title": "Integer Overflow", "type": "Warning"}, {"address": 920, "code": "balances[msg.sender] /* \u786e\u8ba4\u9501\u4ed3\u65f6\u95f4\u662f\u5426\u5230\u4e86\uff0c\u7ed3\u675f\u9501\u4ed3 */ += /*\u4f7f\u7528\u8bf4\u660e*/ msg.value", "contract": "TimeLock", "debug": "storage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0x744240060f11ee8302555055dccca6b72611ae29090e239231b0a7b8f29ae057\ncallvalue: 0xd7ee0142c5f24581862400cc4785a2910417ad282802609755ac30ac4c9e435d\ncalldata_TimeLock[0]: 0xd0e30db000000000000000000000000000000000000000000000000000000000\ncalldatasize_TimeLock: 0x4\n", "description": "A possible integer overflow exists in the function `deposit()`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "sol_unicode.sol", "function": "deposit()", "lineno": 6, "title": "Integer Overflow", "type": "Warning"}, {"address": 933, "code": "now + /*\u4f7f\u7528\u8bf4\u660e*/ 1 weeks", "contract": "TimeLock", "debug": "timestamp: 0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc8780\ncalldata_TimeLock[0]: 0xd0e30db000000000000000000000000000000000000000000000000000000000\ncalldatasize_TimeLock: 0x4\n", "description": "A possible integer overflow exists in the function `deposit()`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "sol_unicode.sol", "function": "deposit()", "lineno": 7, "title": "Integer Overflow", "type": "Warning"}], "success": true}
```

**Comment by norhh** [comment]
just to confirm it's the unicode error right? not the #446 or `No contract was created` message for that commit.

**Comment by shashank-srikant** [comment]
?
the output of the contract you shared?
i see no error when i run it. it runs fine. i've shared the output in my comment above.

**Comment by norhh** [comment]
oops i mean the original contract of the issue.

**Comment by norhh** [comment]
@shashank-srikant thanks for the swift replies, also can you check whether #481 fixes it or not, that would be quite helpful as I can't check it in my pc.

**Comment by norhh** [comment]
@shashank-srikant can you check whether #481 fixes this or not whenever you are free? That would be quite helpful.

**Comment by shashank-srikant** [comment]
sure; had been held up these last two weeks
will check and get back

**Comment by norhh** [comment]
hey @shashank-srikant , any updates?

**Comment by norhh** [comment]
Hey @shashank-srikant I am closing this as this has become stale, If the problem still persists then you can just reopen this issue.
